/xyz/openbmc_project/control/host0/power_cap:
    - Interface: xyz.openbmc_project.Control.Power.Cap
      Properties:
          PowerCap:
              Default: 90
              Validation:
                  Type: "range"
                  Validator: "90..500"
                  Unit: "Watts"
          PowerCapEnable:
              Default: 'true'
