/xyz/openbmc_project/control/host0/soc_power:
    - Interface: xyz.openbmc_project.Control.Power.Soc
      Properties:
          SocPowerLimit:
              Default: 90
              Validation:
                  Type: "range"
                  Validator: "90..500"
                  Unit: "Watts"

/xyz/openbmc_project/ipmi/sol/eth0:
    - Interface: xyz.openbmc_project.Ipmi.SOL
      Properties:
          Enable:
              Default: 'true'
          Privilege:
              Default: 4
          Progress:
              Default: 0
          RetryCount:
              Default: 7
          RetryIntervalMS:
              Default: 100
          Threshold:
              Default: 1

/xyz/openbmc_project/ipmi/sol/eth1:
    - Interface: xyz.openbmc_project.Ipmi.SOL
      Properties:
          Enable:
              Default: 'true'
          Privilege:
              Default: 4
          Progress:
              Default: 0
          RetryCount:
              Default: 7
          RetryIntervalMS:
              Default: 100
          Threshold:
              Default: 1
